title: SouYoung Jin
email: souyoung@mit.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://souyoungjin.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: SouYoung Jin # add your name
author-pic: souyoung.jpeg
about-author: I am a postdoctoral associate at the Computer Science and Artificial Intelligence Laboratory (CSAIL) at the Massachusetts Institute of Technology (MIT), working with <a href="http://olivalab.mit.edu/audeoliva.html" target="_blank">Aude Oliva</a>. Previously I earned my PhD in <a href="https://www.cics.umass.edu/" target="_blank">College of Information and Computer Sciences (CICS)</a>, <a href="https://www.umass.edu/" target="_blank">University of Massachusetts, Amherst (UMass Amherst)</a>, where I researched on improving face clustering in videos under <a href="https://people.cs.umass.edu/~elm/" target="_blank">Erik Learned-Miller</a> in the <a href="http://vis-www.cs.umass.edu/" target="_blank">Computer Vision Lab</a>.<br><br>My research interests are in Computer Vision and Machine Learning. Here is <a href="https://people.cs.umass.edu/~souyoungjin/souyoung_cv.pdf" target="_blank"><b>my CV</b></a>.

# Contact links
email: souyoung@umass.edu # Add your Email address
phone: # Add your Phone number
website: souyoungjin.com # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: souyoungjin # Add your Github handle
twitter:  # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier:  # Add your discus identifier

# Tracker
analytics: UA-69053932-1 # Google Analytics

# Paginate
paginate: 8
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
